export const templateBinding = (index_tab: number) => `
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
  content${index_tab} content${index_tab} content${index_tab} content${index_tab} content${index_tab} conten
`;
